-- Supplier development data generated by scripts/generate_seed.py.
-- Source: ../data/csv/supplier-seed-data.csv (Windows-1252).
-- Run the generator again after changing the CSV; do not edit this file by hand.
-- Apply once to a new hosted development project with db push --include-seed.
-- Supabase also applies it on first local start and on local db reset.
BEGIN;

DO $supplier_seed$
DECLARE
    inserted_supplier_id uuid;
BEGIN
    -- Anna's x Soup Union
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Anna''s x Soup Union', 'Central Library', 'Next to NUS Co-op', '1', 1.296444, 103.773032, '09:00', '18:00', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/ANNA.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- NUS Co-op
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('NUS Co-op', 'Central Library', 'Inside the library on the right side', '1', 1.2967866, 103.7732677, '09:00', '16:00', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/NUS_COOP.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'SHOPPING');

    -- Printer @ Com 2
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Printer @ Com 2', 'Com 2', 'Next to LT19', '1', 1.2938347, 103.7744572, '00:00', '23:59', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/PRINTER_COM2.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'PRINTING');

    -- Cool Spot
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Cool Spot', 'Com2', 'Opp LT16', '1', 1.2940156, 103.7738478, '09:00', '21:30', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/COOL_SPOT.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- InstaChef
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('InstaChef', 'Terrace', 'Next to foyer', '1', 1.2938898, 103.7736305, '00:00', '23:59', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/INSTACHEF.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Cafe+ Robot Cafe
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Cafe+ Robot Cafe', 'Central Library', 'Opp to central library entrance', '1', 1.296444, 103.773032, '00:00', '23:59', 'https://github.com/CS3219-AY2627S1/FoC-Template/blob/main/data/images/ROBOT_CAFE.jpeg')
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD'), (inserted_supplier_id, 'COFFEE');

    -- A Hot Hideout
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('A Hot Hideout', 'Prince George''s Park', 'Near PGP entrance', '2', 1.2908445, 103.7770891, '11:00', '21:30', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Arise and Shine
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Arise and Shine', 'Engineering Block E4', 'Near LT6', '4', 1.2991517, 103.769064, '08:00', '18:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Bakehaus / Aurea
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Bakehaus / Aurea', 'The Ridge', 'Near COM2', '1', 1.2946778, 103.7707872, '08:00', '21:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Central Square @ YIH
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Central Square @ YIH', 'Yusof Ishak House', 'Closest to Opp UHC bus stop', '1', 1.2984401, 103.7726256, '08:00', '20:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Pasta Express
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Pasta Express', 'Frontier', 'Aircon section', '1', 1.2947819, 103.7704435, '09:30', '19:30', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- TOMORO COFFEE
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('TOMORO COFFEE', 'Hon Sui Sen Memorial Library', 'Inside HSSML', '2', 1.2931259, 103.7719943, '08:15', '18:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD'), (inserted_supplier_id, 'COFFEE');

    -- Octobox
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Octobox', 'Prince George’s Park', 'Near PGP entrance', '2', 1.2904347, 103.7787588, '00:00', '23:59', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'SHOPPING');

    -- Smooy
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Smooy', 'COM3', 'The Terrace @ COM3', '1', 1.2948308, 103.7716305, '11:00', '21:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Goh Bros E-Print Pte Ltd
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Goh Bros E-Print Pte Ltd', 'Yusof Ishak House', 'Take the long staircase up YIH', '5', 1.2984905, 103.7720544, '09:00', '18:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'PRINTING');

    -- Cheers Unmanned Convenience Store
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Cheers Unmanned Convenience Store', 'Engineering Block E3', 'Take right from Arise n Shine', '4', 1.2994341, 103.7526298, '00:00', '23:59', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'SHOPPING');

    -- Nami
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Nami', 'innovation4.0', 'Opp TCOMS', '1', 1.2942982, 103.7708813, '08:00', '17:30', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Supersnacks
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Supersnacks', 'Prince George’s Park', 'At level 1 in Prince George''s Park Residences, Block 10', '1', 1.2913847, 103.7776367, '11:00', '02:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD');

    -- Good Day Cafe
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('Good Day Cafe', 'Medicine+Science Library', 'Inside MedScience library', '1', 1.2967989, 103.7794336, '07:30', '18:30', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD'), (inserted_supplier_id, 'COFFEE');

    -- The Coffee Roaster
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('The Coffee Roaster', 'Blk AS8', 'Behind central library bus stop', '1', 1.296252229, 103.7720926, '08:00', '17:30', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD'), (inserted_supplier_id, 'COFFEE');

    -- he by He Brews
    INSERT INTO supplier_service.suppliers (name, building_area, pickup_location_description, floor, latitude, longitude, opening_time, closing_time, image_url)
    VALUES ('he by He Brews', 'Engineering Block EA', 'Near LT7 & Engineering Auditorium', '1', 1.300566804, 103.7707577, '08:00', '17:00', NULL)
    RETURNING id INTO inserted_supplier_id;
    INSERT INTO supplier_service.supplier_categories (supplier_id, category_code)
    VALUES (inserted_supplier_id, 'FOOD'), (inserted_supplier_id, 'COFFEE');

END;
$supplier_seed$;

COMMIT;
